### ISSUE TITLE
Unable to specify multiple highlightjslanguages 

### ISSUE THREAD

**Issue by gamingrobot** [htr3n/hyde-hyde#27]
After this change you can no longer specify a list of additional languages to include in the `config.toml`

https://github.com/htr3n/hyde-hyde/commit/f4aa888a5cdae4eb6109ef198e8e442320a761d1#diff-50f77d49a876973d54d356c7d6f08517L3

**Comment by htr3n** [comment]
@gamingrobot : thanks for reporting this issue. Now languages can be specified in `config.toml` in the `[params]` as following.

```toml
[params]
highlightjslanguages = ["go", "swift", "objectivec"]
```

Please let me know if it works for you.
